version: '3.7'

services:
  web:
    build:
      context: ./cms_src
      dockerfile: Dockerfile.prod
    command: gunicorn personal_cms.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ${STATIC_FILES_HOST}:/usr/src/cms/staticfiles
    ports:
      - 127.0.0.1:8000:8000
    env_file: .env
    depends_on:
      - db
  db:
    image: mariadb
    volumes:
      - postgres_data:/var/lib/mariadb/data/
    env_file: .env.db

volumes:
  postgres_data:
  static_volume: 
